version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.4
    working_directory: /go/src/github.com/containers-ai/karina
    steps:
      - checkout
      - run: cd /go/src/github.com/containers-ai/karina/operator; make manager
      - run: cd /go/src/github.com/containers-ai/karina/datahub; make datahub
      - persist_to_workspace:
          root: /go
          paths:
            - pkg/linux_amd64
            - bin
            - out      
      
workflows:
  version: 2
  build_test:
    jobs:
      - build
